@baseUrl=http://localhost:3000/apis/article
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJpYXQiOjE1OTI3OTgzODl9.blE9QlCk-D7jzvaMKzvty7Lv57mjiPBfrNSJWGoR1pE

### 新增文章
POST {{baseUrl}} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: {{token}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="cover"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"; 

{
    "title":"标题",
    "description":"描述",
    "body":"正文",
    "tags":[2]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 删除文章
DELETE {{baseUrl}}/4 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}


### 获取文章
GET {{baseUrl}}/1?limit=10&tags=[1] HTTP/1.1
Authorization: {{token}}